return {
  "sindrets/diffview.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  cmd = {
    "DiffviewOpen",
    "DiffviewClose",
    "DiffviewToggleFiles",
    "DiffviewFocusFiles",
    "DiffviewRefresh",
    "DiffviewFileHistory",
  },
  keys = {
    { "<leader>gdo", "<cmd>DiffviewOpen<cr>", desc = "Open Diffview" },
    { "<leader>gdc", "<cmd>DiffviewClose<cr>", desc = "Close Diffview" },
    { "<leader>gdh", "<cmd>DiffviewFileHistory %<cr>", desc = "File History (current file)" },
    { "<leader>gdH", "<cmd>DiffviewFileHistory<cr>", desc = "File History (all files)" },
    { "<leader>gdf", "<cmd>DiffviewToggleFiles<cr>", desc = "Toggle Diffview Files" },
    { "<leader>gdr", "<cmd>DiffviewRefresh<cr>", desc = "Refresh Diffview" },
  },
  opts = {
    diff_binaries = false,
    enhanced_diff_hl = false,
    git_cmd = { "git" },
    use_icons = true,
    watch_index = true,
    icons = {
      folder_closed = "",
      folder_open = "",
    },
    signs = {
      fold_closed = "",
      fold_open = "",
      done = "✓",
    },
    view = {
      default = {
        layout = "diff2_horizontal",
        winbar_info = false,
      },
      merge_tool = {
        layout = "diff3_horizontal",
        disable_diagnostics = true,
        winbar_info = true,
      },
      file_history = {
        layout = "diff2_horizontal",
        winbar_info = false,
      },
    },
    file_panel = {
      listing_style = "tree",
      tree_options = {
        flatten_dirs = true,
        folder_statuses = "only_folded",
      },
      win_config = {
        position = "left",
        width = 35,
        win_opts = {},
      },
    },
    file_history_panel = {
      log_options = {
        git = {
          single_file = {
            diff_merges = "combined",
          },
          multi_file = {
            diff_merges = "first-parent",
          },
        },
      },
      win_config = {
        position = "bottom",
        height = 16,
        win_opts = {},
      },
    },
    commit_log_panel = {
      win_config = {},
    },
    default_args = {
      DiffviewOpen = {},
      DiffviewFileHistory = {},
    },
    hooks = {},
    keymaps = {
      disable_defaults = false,
      view = {
        { "n", "<tab>", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle file panel" } },
        { "n", "gf", "<cmd>DiffviewGotoFile<cr>", { desc = "Open file in previous tab" } },
        { "n", "<C-w><C-f>", "<cmd>DiffviewGotoFileTab<cr>", { desc = "Open file in new tab" } },
        { "n", "<C-w>gf", "<cmd>DiffviewGotoFileSplit<cr>", { desc = "Open file in split" } },
        { "n", "<leader>e", "<cmd>DiffviewFocusFiles<cr>", { desc = "Focus file panel" } },
        { "n", "<leader>b", "<cmd>DiffviewToggleBase<cr>", { desc = "Toggle base" } },
        { "n", "g<C-x>", "<cmd>DiffviewCycleLayout<cr>", { desc = "Cycle layout" } },
        { "n", "[x", "<cmd>DiffviewPrevConflict<cr>", { desc = "Previous conflict" } },
        { "n", "]x", "<cmd>DiffviewNextConflict<cr>", { desc = "Next conflict" } },
      },
      diff1 = {
        { "n", "g?", "<cmd>DiffviewHelp diff1<cr>", { desc = "Help" } },
      },
      diff2 = {
        { "n", "g?", "<cmd>DiffviewHelp diff2<cr>", { desc = "Help" } },
      },
      diff3 = {
        { "n", "2do", "<cmd>DiffviewDiffGet theirs<cr>", { desc = "Get theirs" } },
        { "v", "2do", "<cmd>'<,'>DiffviewDiffGet theirs<cr>", { desc = "Get theirs" } },
        { "n", "3do", "<cmd>DiffviewDiffGet ours<cr>", { desc = "Get ours" } },
        { "v", "3do", "<cmd>'<,'>DiffviewDiffGet ours<cr>", { desc = "Get ours" } },
        { "n", "g?", "<cmd>DiffviewHelp diff3<cr>", { desc = "Help" } },
      },
      diff4 = {
        { "n", "1do", "<cmd>DiffviewDiffGet base<cr>", { desc = "Get base" } },
        { "v", "1do", "<cmd>'<,'>DiffviewDiffGet base<cr>", { desc = "Get base" } },
        { "n", "2do", "<cmd>DiffviewDiffGet theirs<cr>", { desc = "Get theirs" } },
        { "v", "2do", "<cmd>'<,'>DiffviewDiffGet theirs<cr>", { desc = "Get theirs" } },
        { "n", "3do", "<cmd>DiffviewDiffGet ours<cr>", { desc = "Get ours" } },
        { "v", "3do", "<cmd>'<,'>DiffviewDiffGet ours<cr>", { desc = "Get ours" } },
        { "n", "g?", "<cmd>DiffviewHelp diff4<cr>", { desc = "Help" } },
      },
      file_panel = {
        { "n", "j", "<cmd>DiffviewNextEntry<cr>", { desc = "Next entry" } },
        { "n", "<down>", "<cmd>DiffviewNextEntry<cr>", { desc = "Next entry" } },
        { "n", "k", "<cmd>DiffviewPrevEntry<cr>", { desc = "Previous entry" } },
        { "n", "<up>", "<cmd>DiffviewPrevEntry<cr>", { desc = "Previous entry" } },
        { "n", "<cr>", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "o", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "l", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "<2-LeftMouse>", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "-", "<cmd>DiffviewToggleStage<cr>", { desc = "Toggle stage" } },
        { "n", "s", "<cmd>DiffviewToggleStage<cr>", { desc = "Toggle stage" } },
        { "n", "S", "<cmd>DiffviewStageAll<cr>", { desc = "Stage all" } },
        { "n", "u", "<cmd>DiffviewUnstageAll<cr>", { desc = "Unstage all" } },
        { "n", "X", "<cmd>DiffviewRestoreEntry<cr>", { desc = "Restore entry" } },
        { "n", "L", "<cmd>DiffviewOpenCommitLog<cr>", { desc = "Open commit log" } },
        { "n", "zo", "<cmd>DiffviewOpenFold<cr>", { desc = "Open fold" } },
        { "n", "h", "<cmd>DiffviewCloseFold<cr>", { desc = "Close fold" } },
        { "n", "zc", "<cmd>DiffviewCloseFold<cr>", { desc = "Close fold" } },
        { "n", "za", "<cmd>DiffviewToggleFold<cr>", { desc = "Toggle fold" } },
        { "n", "zR", "<cmd>DiffviewOpenAllFolds<cr>", { desc = "Open all folds" } },
        { "n", "zM", "<cmd>DiffviewCloseAllFolds<cr>", { desc = "Close all folds" } },
        { "n", "<c-b>", "<cmd>DiffviewScrollUp<cr>", { desc = "Scroll up" } },
        { "n", "<c-f>", "<cmd>DiffviewScrollDown<cr>", { desc = "Scroll down" } },
        { "n", "<tab>", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle files" } },
        { "n", "q", "<cmd>DiffviewClose<cr>", { desc = "Close" } },
        { "n", "R", "<cmd>DiffviewRefresh<cr>", { desc = "Refresh" } },
        { "n", "gf", "<cmd>DiffviewGotoFile<cr>", { desc = "Go to file" } },
        { "n", "<C-w><C-f>", "<cmd>DiffviewGotoFileTab<cr>", { desc = "Go to file in tab" } },
        { "n", "i", "<cmd>DiffviewFlattenDirs<cr>", { desc = "Flatten dirs" } },
        { "n", "g<C-x>", "<cmd>DiffviewCycleLayout<cr>", { desc = "Cycle layout" } },
        { "n", "g?", "<cmd>DiffviewHelp file_panel<cr>", { desc = "Help" } },
      },
      file_history_panel = {
        { "n", "g!", "<cmd>DiffviewOptionsCall<cr>", { desc = "Options" } },
        { "n", "<C-A-d>", "<cmd>DiffviewOpenDiffTab<cr>", { desc = "Open diff tab" } },
        { "n", "d", "<cmd>DiffviewOpenDiffTab<cr>", { desc = "Open diff tab" } },
        { "n", "zR", "<cmd>DiffviewOpenAllFolds<cr>", { desc = "Open all folds" } },
        { "n", "zM", "<cmd>DiffviewCloseAllFolds<cr>", { desc = "Close all folds" } },
        { "n", "j", "<cmd>DiffviewNextEntry<cr>", { desc = "Next entry" } },
        { "n", "<down>", "<cmd>DiffviewNextEntry<cr>", { desc = "Next entry" } },
        { "n", "k", "<cmd>DiffviewPrevEntry<cr>", { desc = "Previous entry" } },
        { "n", "<up>", "<cmd>DiffviewPrevEntry<cr>", { desc = "Previous entry" } },
        { "n", "<cr>", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "o", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "l", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "<2-LeftMouse>", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "<tab>", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle files" } },
        { "n", "q", "<cmd>DiffviewClose<cr>", { desc = "Close" } },
        { "n", "R", "<cmd>DiffviewRefresh<cr>", { desc = "Refresh" } },
        { "n", "gf", "<cmd>DiffviewGotoFile<cr>", { desc = "Go to file" } },
        { "n", "<C-w><C-f>", "<cmd>DiffviewGotoFileTab<cr>", { desc = "Go to file in tab" } },
        { "n", "g<C-x>", "<cmd>DiffviewCycleLayout<cr>", { desc = "Cycle layout" } },
        { "n", "g?", "<cmd>DiffviewHelp file_history_panel<cr>", { desc = "Help" } },
      },
      option_panel = {
        { "n", "<tab>", "<cmd>DiffviewSelectEntry<cr>", { desc = "Select entry" } },
        { "n", "q", "<cmd>DiffviewClose<cr>", { desc = "Close" } },
        { "n", "g?", "<cmd>DiffviewHelp option_panel<cr>", { desc = "Help" } },
      },
      help_panel = {
        { "n", "q", "<cmd>DiffviewClose<cr>", { desc = "Close" } },
      },
    },
  },
}